# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [54]:
print(np.version.version)
np.show_config()

1.23.1
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

#### 3. Create a null vector of size 10 (★☆☆)

In [82]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [56]:
answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [83]:
print(v.size)
print(v.itemsize)
print("%d bytes" % (v.size * v.itemsize))

10
8
80 bytes


In [58]:
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [77]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [74]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [79]:
v = np.zeros(10,int)
v[4] = 1
print(v)

[0 0 0 0 1 0 0 0 0 0]


In [88]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [94]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [87]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [98]:
v = np.flip(v)
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [96]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [107]:
m = np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [106]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [128]:
v = np.array([1,2,0,0,4,0])
w = np.nonzero(v)
print(w)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [137]:
v = np.identity(3,int)
print(v)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [138]:
answer(11)

Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [145]:
v =np.random.random((3,3,3))
print(v)

[[[0.90439815 0.3324744  0.03226612]
  [0.6681667  0.05128519 0.41609939]
  [0.27933945 0.6427734  0.54798253]]

 [[0.57862936 0.78308377 0.20403889]
  [0.01949973 0.74244111 0.03828307]
  [0.48896294 0.19915892 0.03686947]]

 [[0.48070633 0.14797659 0.56955522]
  [0.42494168 0.57440604 0.5529065 ]
  [0.18640928 0.10442408 0.99163748]]]


In [147]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [158]:
v = np.random.random((10,10))
vmin,vmax = v.min(), v.max()
print(vmin,vmax)

0.004241830869802232 0.9684837068841292


In [152]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [164]:
v = np.random.random(30)
print(v)
m = v.mean()
print(m)

[0.58084589 0.65481829 0.41426258 0.69562878 0.77641698 0.16736575
 0.3694237  0.52375943 0.93603434 0.01165415 0.58896993 0.28792705
 0.77731948 0.1796463  0.05045359 0.86133383 0.33508774 0.05326298
 0.93383433 0.67827712 0.63734246 0.41551731 0.17647595 0.44319926
 0.31771206 0.86497127 0.74526075 0.72060589 0.8402806  0.33390506]
0.5123864279363538


In [165]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [173]:
v = np.ones((5,5))
v[1:-1,1:-1] = 0

print(v)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [174]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [193]:
v = np.ones((5,5))
v[:, [0, -1]] = 0
v[[0, -1], :] = 0

print(v)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [5]:
answer(17)

print(0 * np.nan)               #NAN
print(np.nan == np.nan)         #False
print(np.inf > np.nan)          #False
print(np.nan - np.nan)          #NAN
print(np.nan in set([np.nan]))  #True
print(0.3 == 3 * 0.1)           #False

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [14]:
M = np.zeros((5,5),int)
for i in range(0,len(M)-1):
    M[i+1,i] = i+1

print(M)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

answer(18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [32]:
M = np.zeros((8,8),int)

M[1::2,1::2] = 1
M[::2,::2] = 1

print(M)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [31]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [55]:
M = np.zeros(6*7*8,int)
M[99] = 1
M = M.reshape(6,7,8)

N = np.unravel_index(99, (6,7,8))
print(N)

print(M[1,5,3])


(1, 5, 3)
1


In [56]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [86]:
M = np.tile(np.diag((1,1)),(4,4))
print(M)

answer(21)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [92]:
M = np.random.random((5,5))
M = (M - np.mean(M))/ np.std(M)
print(M)

answer(22)

[[-1.31612781  1.02617554  0.22574741  1.1965941  -0.36695572]
 [-1.29493761 -0.89065118 -0.37454547 -0.42996452  0.06228639]
 [ 1.46949593 -0.8499146  -1.55633699 -0.59115559  1.54347713]
 [ 0.87404975 -0.71060784 -1.50715966  0.95001387 -0.88030035]
 [-0.4157593   1.50570268  0.33567649  1.02425874  0.97093863]]
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [96]:
dt = np.dtype((np.void,4))

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [99]:
A = np.ones((5,3))
B = np.ones((3,2))

C = np.matmul(A,B)
print(C)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

answer(24)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [104]:
M = np.arange(1,10)
M[2:7] = -M[2:7]

print(M)

answer(25)

[ 1  2 -3 -4 -5 -6 -7  8  9]
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [109]:
print(sum(range(1,5),-1))
from numpy import *
print(sum(range(1,5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [113]:
Z**Z
#2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [114]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\chans\AppData\Local\Temp\ipykernel_4816\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\chans\AppData\Local\Temp\ipykernel_4816\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)